### ISSUE TITLE
想问一下这个项目是基于qqwweee的keras-yolo3的吗？

### ISSUE THREAD

**Issue by wutianze** [SpikeKing/keras-yolo3-detection#35]
大佬，问一下这个项目是基于qqwweee的keras-yolo3的吗？
因为自己之前用它那个训练了一个自己的yolo，但很多东西都不理解，所以想跟着大佬学习一下，如果两个版本是大致兼容的我心里会更加有底一些。

**Comment by boreas-l** [comment]
> 大佬，问一下这个项目是基于qqwweee的keras-yolo3的吗？
> 因为自己之前用它那个训练了一个自己的yolo，但很多东西都不理解，所以想跟着大佬学习一下，如果两个版本是大致兼容的我心里会更加有底一些。

说实话，我对比过，很像很像。感觉就跟照搬没啥区别了
