### ISSUE TITLE
对于model.py文件有一些问题

### ISSUE THREAD

**Issue by gittigxuy** [SpikeKing/keras-yolo3-detection#6]
不知道博主大大是否看懂了这个文件网络结构的搭建，如果理解的话可否写一个博客解析一下这个文件的内容。
我有一个问题，对于make_last_layers我的理解是，将目标输出分为3类，输出结果分别是13*13,26*26,52*52，但是我没有看到具体实现。

**Comment by SpikeKing** [comment]
我正在梳理源码中，可能会继续写一篇细节。

**Comment by gittigxuy** [comment]
好的，写好之后记得@我，谢谢了

**Comment by gittigxuy** [comment]
@SpikeKing ,请问源码梳理的如何了呢？可否写个细节博客呢？

**Comment by gittigxuy** [comment]
@SpikeKing ,感谢，抽空看，在用你这个框架训练RAP数据集，训练好之后在issue当中分享结果

**Comment by SpikeKing** [comment]
这个文章里面，有网络部分的细节！
