### ISSUE TITLE
关于cfg文件

### ISSUE THREAD

**Issue by mengzhibin** [SpikeKing/keras-yolo3-detection#9]
由于我们是训练单类，cfg文件中的class和最后一层的输出filter数量，是不是应该修改啊？

**Comment by SpikeKing** [comment]
不用的，cfg是基础网络，最后通过类别文件，输出不同类别。

**Comment by gittigxuy** [comment]
@mengzhibin ,同意作者的观点，不需要更改cfg文件，我们可以通过convert.py文件将cfg文件转化为.h5文件这个预训练模型，我们修改train.py的最终输出的classes来进行分类即可
